# Generated by Django 4.1.6 on 2023-04-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeframe',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=10),
        ),
    ]
