# Generated by Django 4.1.6 on 2023-04-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='courses_to_tutor',
            field=models.ManyToManyField(to='base.course'),
        ),
    ]
