# Generated by Django 4.1.6 on 2023-04-04 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tutor_courses_to_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='courses_to_tutor',
        ),
        migrations.CreateModel(
            name='CourseTutored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tutor')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_all_tutors',
            field=models.ManyToManyField(through='base.CourseTutored', to='base.tutor'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_all_courses',
            field=models.ManyToManyField(through='base.CourseTutored', to='base.course'),
        ),
    ]
