# Generated by Django 4.1.6 on 2023-04-19 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_timeframe_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeframe',
            name='tutor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.tutor'),
        ),
    ]
