# Generated by Django 4.1.6 on 2023-04-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_timeframe_tutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeFrame',
        ),
    ]
