# Generated by Django 4.1.6 on 2023-04-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_tutor_courses_to_tutor_coursetutored_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='mnem',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='descr',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='num',
            new_name='number',
        ),
    ]
