# Generated by Django 4.1.6 on 2023-04-02 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.CharField(default='', max_length=40)),
                ('time_frames', models.CharField(default='', max_length=40)),
                ('classes', models.TextField(default='', max_length=1000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='Studentss',
        ),
        migrations.AddField(
            model_name='tutor',
            name='hourly_rate',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='time_frames',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
    ]
