# Generated by Django 4.1.6 on 2023-04-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_notification_student_stduent_all_tutors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='info',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
