# Generated by Django 4.1.6 on 2023-04-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_timeframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeframe',
            name='date',
        ),
    ]
