# Generated by Django 4.1.6 on 2023-04-15 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_notification_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stduent_all_tutors',
            new_name='student_all_tutors',
        ),
    ]
